#!/usr/bin/env node
// Regenerates the Mermaid dependency graph of docs/ROADMAP.md §4 from docs/milestones.yaml.
//
//   node scripts/deps-graph.mjs --write   rewrite the block between the deps-graph markers
//   node scripts/deps-graph.mjs --check   exit 1 if the block, or milestones.yaml itself, has
//                                         drifted from ROADMAP.md; change nothing
//
// Edges are written in the pipe form (`A -->|label| B`, `A -.->|label| B`): Mermaid's other
// dotted form, `A -. label .-> B`, fails to parse when the label contains a dot (checked with
// mermaid 12.0.0's `mermaid.parse`), which labels such as "U1.2 exact version" do.
//
// Besides rendering, the script checks milestones.yaml against the prose it encodes: for every
// `### Mn` / `### Un` section of ROADMAP.md, the ids named in its "Dependencies" and "Upstream"
// bullets must be exactly the ids milestones.yaml records for it (see the header of that file).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ROADMAP = path.join(repo, 'docs', 'ROADMAP.md');
const DATA = path.join(repo, 'docs', 'milestones.yaml');
const START = '<!-- deps-graph:start: generated by scripts/deps-graph.mjs from docs/milestones.yaml; edit that file, then run `npm run docs:graph` -->';
const END = '<!-- deps-graph:end -->';

const problems = [];
const problem = (msg) => problems.push(msg);

// ---------------------------------------------------------------------------------------------
// Load and validate milestones.yaml
// ---------------------------------------------------------------------------------------------

const data = parse(fs.readFileSync(DATA, 'utf8'));
const tracks = data.tracks ?? [];
const milestones = data.milestones ?? [];
const nodes = new Map([...milestones, ...tracks].map((n) => [n.id, n]));
const orNodes = milestones.filter((m) => m.oneOf).map((m) => m.oneOf);

// The Map above keeps one entry per id, but render() draws every entry of the lists, so a
// copy-pasted duplicate would reach ROADMAP.md as a second node line with every check green.
function checkUnique(what, ids) {
  const seen = new Set();
  for (const id of ids) {
    if (seen.has(id)) { problem(`${what} id ${JSON.stringify(id)} appears more than once in milestones.yaml`); }
    seen.add(id);
  }
}
checkUnique('node', [...milestones, ...tracks].map((n) => n.id));
checkUnique('oneOf', orNodes.map((o) => o.id));
const trackOfItem = (item) => /^(U\d+)(?:\.\d+)?$/.exec(item)?.[1];
const entryId = (e) => (typeof e === 'string' ? e : e.id);
const entryLabel = (e) => (typeof e === 'string' ? undefined : e.label);

const BAD_EDGE_LABEL = /[|"()[\]{}]/;
function checkNodeLabel(owner, label) {
  if (typeof label !== 'string' || label === '' || label.includes('"')) {
    problem(`${owner}: node label ${JSON.stringify(label)} must be a non-empty string without '"'`);
  }
}
function checkEdgeLabel(owner, label) {
  if (label !== undefined && (typeof label !== 'string' || BAD_EDGE_LABEL.test(label))) {
    problem(`${owner}: edge label ${JSON.stringify(label)} contains a character Mermaid cannot take in an edge label`);
  }
}
function checkRef(owner, id) {
  if (!nodes.has(id)) {
    problem(`${owner}: unknown id ${JSON.stringify(id)}`);
  }
}

for (const n of [...milestones, ...tracks]) {
  checkNodeLabel(n.id, n.label);
}
for (const t of tracks) {
  for (const o of t.optional ?? []) { checkRef(t.id, o.from); checkEdgeLabel(t.id, o.label); }
}
for (const m of milestones) {
  for (const r of m.requires ?? []) { checkRef(m.id, entryId(r)); checkEdgeLabel(m.id, entryLabel(r)); }
  for (const o of m.optional ?? []) { checkRef(m.id, o.from); checkEdgeLabel(m.id, o.label); }
  for (const n of m.notRequired ?? []) { checkRef(m.id, n.id); }
  if (m.oneOf) {
    checkNodeLabel(`${m.id} oneOf`, m.oneOf.label);
    if (nodes.has(m.oneOf.id)) { problem(`${m.id}: oneOf id ${m.oneOf.id} clashes with a node id`); }
    if ((m.oneOf.members ?? []).length < 2) { problem(`${m.id}: oneOf needs at least two members`); }
    for (const x of m.oneOf.members ?? []) { checkRef(m.id, x); }
  }
  for (const u of m.upstream ?? []) {
    checkEdgeLabel(m.id, u.label);
    const ts = new Set((u.items ?? []).map(trackOfItem));
    if (ts.size !== 1 || ts.has(undefined) || !tracks.some((t) => ts.has(t.id))) {
      problem(`${m.id}: upstream items ${JSON.stringify(u.items)} must all belong to one declared track`);
    }
  }
}

// Hard dependencies must be acyclic (optional edges may form cycles: M9 and M11 enhance each other).
{
  const state = new Map();
  const hardDeps = (id) => {
    const m = milestones.find((x) => x.id === id);
    return m ? [...(m.requires ?? []).map(entryId), ...(m.oneOf?.members ?? [])] : [];
  };
  const visit = (id, trail) => {
    if (state.get(id) === 'done') { return; }
    if (state.get(id) === 'active') { problem(`cycle of hard dependencies: ${[...trail, id].join(' -> ')}`); return; }
    state.set(id, 'active');
    for (const d of hardDeps(id)) { visit(d, [...trail, id]); }
    state.set(id, 'done');
  };
  milestones.forEach((m) => visit(m.id, []));
}

// ---------------------------------------------------------------------------------------------
// Compare with the prose of ROADMAP.md
// ---------------------------------------------------------------------------------------------

const roadmap = fs.readFileSync(ROADMAP, 'utf8');
const sections = new Map();
for (const s of roadmap.split(/^(?=### )/m)) {
  const m = /^### ([MU]\d+) /.exec(s);
  if (m) { sections.set(m[1], s); }
}

/** The text of the `- **Name.**` bullet of a section (up to the next bullet or heading). */
function bullet(section, name) {
  const m = new RegExp(`^- \\*\\*${name}\\.\\*\\*([\\s\\S]*?)(?=^- \\*\\*|^#|^---|(?![\\s\\S]))`, 'm').exec(section);
  return m?.[1];
}
const idsIn = (text, re) => new Set(text.match(re) ?? []);
const sameSet = (a, b) => a.size === b.size && [...a].every((x) => b.has(x));
const fmt = (s) => `{${[...s].sort().join(', ')}}`;

for (const id of sections.keys()) {
  if (!nodes.has(id)) { problem(`ROADMAP.md has a section "### ${id}" that milestones.yaml does not list`); }
}
for (const n of [...milestones, ...tracks]) {
  const section = sections.get(n.id);
  if (section === undefined) { problem(`milestones.yaml lists ${n.id}, which has no "### ${n.id}" section in ROADMAP.md`); continue; }
  const isTrack = tracks.includes(n);

  let depsText = bullet(section, 'Dependencies');
  if (depsText === undefined) {
    const sentences = section.match(/Depends on [^.]*\./g);
    depsText = sentences?.join(' ') ?? '';
  }
  const named = idsIn(depsText, isTrack ? /\bU\d+\b/g : /\bM\d+\b/g);
  const recorded = new Set(isTrack
    ? (n.optional ?? []).map((o) => o.from)
    : [...(n.requires ?? []).map(entryId), ...(n.oneOf?.members ?? []), ...(n.optional ?? []).map((o) => o.from),
      ...(n.notRequired ?? []).map((x) => x.id)]);
  if (!sameSet(named, recorded)) {
    problem(`${n.id}: the Dependencies text names ${fmt(named)} but milestones.yaml records ${fmt(recorded)}`);
  }

  if (!isTrack) {
    const up = idsIn(bullet(section, 'Upstream') ?? '', /\bU\d+(?:\.\d+)?\b/g);
    const upRecorded = new Set((n.upstream ?? []).flatMap((u) => u.items ?? []));
    if (!sameSet(up, upRecorded)) {
      problem(`${n.id}: the Upstream text names ${fmt(up)} but milestones.yaml records ${fmt(upRecorded)}`);
    }
  }
}

// ---------------------------------------------------------------------------------------------
// Render
// ---------------------------------------------------------------------------------------------

function render() {
  const out = ['```mermaid', 'graph TD'];
  for (const m of milestones) { out.push(`  ${m.id}["${m.label}"]`); }
  for (const o of orNodes) { out.push(`  ${o.id}{{"${o.label}"}}`); }
  for (const t of tracks) { out.push(`  ${t.id}["${t.label}"]`); }

  out.push('', '  %% hard dependencies (every dependency listed in §5 is drawn, including ones implied transitively)');
  for (const m of milestones) {
    for (const r of m.requires ?? []) {
      const label = entryLabel(r);
      out.push(label ? `  ${entryId(r)} -->|${label}| ${m.id}` : `  ${entryId(r)} --> ${m.id}`);
    }
    if (m.oneOf) { out.push(`  ${m.oneOf.id} --> ${m.id}`); }
  }

  out.push('', '  %% OR nodes: one of the members suffices');
  for (const o of orNodes) {
    o.members.forEach((x, i) => out.push(`  ${x} -.->|${i === 0 ? 'either' : 'or'}| ${o.id}`));
  }

  out.push('', '  %% optional enhancements');
  for (const m of milestones) {
    for (const o of m.optional ?? []) { out.push(`  ${o.from} -.->|${o.label}| ${m.id}`); }
  }

  out.push('', '  %% upstream enablers');
  for (const t of tracks) {
    for (const o of t.optional ?? []) { out.push(`  ${o.from} -.->|${o.label}| ${t.id}`); }
  }
  for (const m of milestones) {
    for (const u of m.upstream ?? []) { out.push(`  ${trackOfItem(u.items[0])} -.->|${u.label}| ${m.id}`); }
  }

  out.push('', '  classDef up fill:#fff3cd,stroke:#b58900;', `  class ${tracks.map((t) => t.id).join(',')} up;`, '```');
  return out.join('\n');
}

// ---------------------------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------------------------

const mode = process.argv[2];
if (process.argv.length !== 3 || (mode !== '--write' && mode !== '--check')) {
  console.error('usage: node scripts/deps-graph.mjs --write | --check');
  process.exit(2);
}

const starts = roadmap.split(START).length - 1;
const ends = roadmap.split(END).length - 1;
if (starts !== 1 || ends !== 1 || roadmap.indexOf(START) > roadmap.indexOf(END)) {
  problem(`ROADMAP.md must contain exactly one "${START}" line followed by one "${END}" line`);
}
if (problems.length > 0) {
  problems.forEach((p) => console.error(`deps-graph: ${p}`));
  process.exit(1);
}

const before = roadmap.slice(0, roadmap.indexOf(START) + START.length);
const after = roadmap.slice(roadmap.indexOf(END));
const updated = `${before}\n${render()}\n${after}`;

if (mode === '--write') {
  if (updated !== roadmap) { fs.writeFileSync(ROADMAP, updated); }
  console.log(updated === roadmap ? 'deps-graph: ROADMAP.md already up to date' : 'deps-graph: ROADMAP.md §4 graph rewritten');
} else if (updated !== roadmap) {
  console.error('deps-graph: the §4 graph in ROADMAP.md differs from docs/milestones.yaml; run `npm run docs:graph`');
  process.exit(1);
} else {
  console.log('deps-graph: ROADMAP.md §4 graph matches docs/milestones.yaml');
}
